# permissions for end users to view humans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: human-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s
    app.kubernetes.io/part-of: k8s
    app.kubernetes.io/managed-by: kustomize
  name: human-viewer-role
rules:
- apiGroups:
  - mammals.example.com
  resources:
  - humans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mammals.example.com
  resources:
  - humans/status
  verbs:
  - get
