---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
- apiGroups:
  - mammals.example.com
  resources:
  - humans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mammals.example.com
  resources:
  - humans/finalizers
  verbs:
  - update
- apiGroups:
  - mammals.example.com
  resources:
  - humans/status
  verbs:
  - get
  - patch
  - update
